train: true
model_name: "yolo12n"

project_name: "EyeInTheSky"
dataset_name: "VisDrone"

raw_data_dir: "data/raw"
data_dir: "data"
config_dir: "config"
interim_data_dir: "data/interim"
processed_data_dir: "data/processed"
external_data_dir: "data/external"
models_dir: "models"
reports_dir: "reports"
figures_dir: "reports/figures"

# Ray Tune Configuration
shared_args:
  workers: 8               # Number of data loader workers
  seed: 42                 # Random seed
  exist_ok: False          
  cos_lr: True            # Cosine learning rate
  imgsz: 640               # Input image size
  plots: True
  patience: 5             # Early stopping patience
  val: False

# Fixed Training Configuration
train:
  project: "models"
  name: "YOLOv12-VisDrone-Training"
  epochs: 10             # Number of training epochs
  save: True              # Save checkpoints
  save_period: 10         # Save every X epochs

val:
  half: True
  conf: 0.25
  iou: 0.6

tune:
  fixed_args:
    project: "models"
    name: "YOLOv12-VisDrone-Tuning"
    epochs: 3   
    iterations: 3
    batch_size: 16
    workers: 8
    seed: 42
    plots: True
    val: False
    cos_lr: True
    use_ray: True
    imgsz: 640 
    exist_ok: True
    save: True
    save_period: 10
    cache: True

wandb:
  dir: "reports/"